### ISSUE TITLE
ADD fzf & fzf-tabs 

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/AnubisIDE#2]
These are great tools, lets add them: 

https://github.com/Aloxaf/fzf-tab

**Comment by GusSand** [comment]
Are these gonna go in the student images?

**Comment by wabscale** [comment]
They already are. You can try it out on playgrounds now. It makes a really big difference to autocomplete ![Screenshot_2022-08-27_at_14-55-50_anubis_Anubis_IDE.png](https://user-images.githubusercontent.com/36013983/187081713-eba6160e-7a29-4504-b917-dcf095e20110.png)
